spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/sso_db?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT-8
    username: root
    password: 960918
server:
  port: 8090